<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GovernmentAgencies extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('agencies')->insert([
            array('id' => '1', 'sector' => 'Congressional', 'name' => 'Senate', 'created_at' => null, 'updated_at' => null),
            array('id' => '2', 'sector' => 'Congressional', 'name' => 'Senate Electoral Tribunal', 'created_at' => null, 'updated_at' => null),
            array('id' => '3', 'sector' => 'Congressional', 'name' => 'Commission on Appointments', 'created_at' => null, 'updated_at' => null),
            array('id' => '4', 'sector' => 'Congressional', 'name' => 'House of Representatives', 'created_at' => null, 'updated_at' => null),
            array('id' => '5', 'sector' => 'Congressional', 'name' => 'House of Electoral Tribunal', 'created_at' => null, 'updated_at' => null),
            array('id' => '6', 'sector' => 'Office of the President', 'name' => 'The President\'s Office', 'created_at' => null, 'updated_at' => null),
            array('id' => '7', 'sector' => 'Office of the Vice President', 'name' => 'The Vice President\'s Office', 'created_at' => null, 'updated_at' => null),
            array('id' => '8', 'sector' => 'Department of Agrarian Reform', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '9', 'sector' => 'Department of Agriculture', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '10', 'sector' => 'Department of Agriculture', 'name' => 'Agricultural Credit Policy Council', 'created_at' => null, 'updated_at' => null),
            array('id' => '11', 'sector' => 'Department of Agriculture', 'name' => 'Bureau of Fisheries and Aquatic Resources', 'created_at' => null, 'updated_at' => null),
            array('id' => '12', 'sector' => 'Department of Agriculture', 'name' => 'National Meat Inspection Service', 'created_at' => null, 'updated_at' => null),
            array('id' => '13', 'sector' => 'Department of Agriculture', 'name' => 'Philippine Carabao Center', 'created_at' => null, 'updated_at' => null),
            array('id' => '14', 'sector' => 'Department of Agriculture', 'name' => 'Philippine Center for Post-Harvest Development and Mechanization', 'created_at' => null, 'updated_at' => null),
            array('id' => '15', 'sector' => 'Department of Agriculture', 'name' => 'Philippine Council for Agriculture and Fisheries', 'created_at' => null, 'updated_at' => null),
            array('id' => '16', 'sector' => 'Department of Agriculture', 'name' => 'Philippines Fiber Industry Development Authority', 'created_at' => null, 'updated_at' => null),
            array('id' => '17', 'sector' => 'Department of Budget and Management', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '18', 'sector' => 'Department of Budget and Management', 'name' => 'Government Procurement Policy Board-Technical Support Office', 'created_at' => null, 'updated_at' => null),
            array('id' => '19', 'sector' => 'Department of Education', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '20', 'sector' => 'Department of Education', 'name' => 'Early Childhood Care and Development Council', 'created_at' => null, 'updated_at' => null),
            array('id' => '21', 'sector' => 'Department of Education', 'name' => 'National Book Development Board', 'created_at' => null, 'updated_at' => null),
            array('id' => '22', 'sector' => 'Department of Education', 'name' => 'National Council for Children\'s Television', 'created_at' => null, 'updated_at' => null),
            array('id' => '23', 'sector' => 'Department of Education', 'name' => 'National Museum', 'created_at' => null, 'updated_at' => null),
            array('id' => '24', 'sector' => 'Department of Education', 'name' => 'Philippines High School for the Arts', 'created_at' => null, 'updated_at' => null),
            array('id' => '25', 'sector' => 'State Universities and Colleges', 'name' => 'Eulogio "Amang" Rodriguez Institute of Science and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '26', 'sector' => 'State Universities and Colleges', 'name' => 'Marikina Polytechnic College (Marikina Institute of Science and Technology)', 'created_at' => null, 'updated_at' => null),
            array('id' => '27', 'sector' => 'State Universities and Colleges', 'name' => 'Philippine Normal University', 'created_at' => null, 'updated_at' => null),
            array('id' => '28', 'sector' => 'State Universities and Colleges', 'name' => 'Philippine State College of Aeronautics', 'created_at' => null, 'updated_at' => null),
            array('id' => '29', 'sector' => 'State Universities and Colleges', 'name' => 'Polytechnic University of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '30', 'sector' => 'State Universities and Colleges', 'name' => 'Rizal Technological University', 'created_at' => null, 'updated_at' => null),
            array('id' => '31', 'sector' => 'State Universities and Colleges', 'name' => 'Technological University of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '32', 'sector' => 'State Universities and Colleges', 'name' => 'University of the Philippines System(The National University)', 'created_at' => null, 'updated_at' => null),
            array('id' => '33', 'sector' => 'State Universities and Colleges', 'name' => 'Don Mariano Marcos Memorial State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '34', 'sector' => 'State Universities and Colleges', 'name' => 'Illocos Sur Polytechnic State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '35', 'sector' => 'State Universities and Colleges', 'name' => 'Mariano Marcos State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '36', 'sector' => 'State Universities and Colleges', 'name' => 'North Luzon Philippines State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '37', 'sector' => 'State Universities and Colleges', 'name' => 'Pangasinan State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '38', 'sector' => 'State Universities and Colleges', 'name' => 'University of Northern Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '39', 'sector' => 'State Universities and Colleges', 'name' => 'Abra State Institute of Science and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '40', 'sector' => 'State Universities and Colleges', 'name' => 'Apayao State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '41', 'sector' => 'State Universities and Colleges', 'name' => 'Benguet State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '42', 'sector' => 'State Universities and Colleges', 'name' => 'Ifugao State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '43', 'sector' => 'State Universities and Colleges', 'name' => 'Kalinga State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '44', 'sector' => 'State Universities and Colleges', 'name' => 'Mountain Provice State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '45', 'sector' => 'State Universities and Colleges', 'name' => 'Batanes State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '46', 'sector' => 'State Universities and Colleges', 'name' => 'Cagayan State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '47', 'sector' => 'State Universities and Colleges', 'name' => 'Isabela State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '48', 'sector' => 'State Universities and Colleges', 'name' => 'Nueva Vizcaya State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '49', 'sector' => 'State Universities and Colleges', 'name' => 'Quirino State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '50', 'sector' => 'State Universities and Colleges', 'name' => 'Aurora State Collage of Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '51', 'sector' => 'State Universities and Colleges', 'name' => 'Bataan Peninsula State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '52', 'sector' => 'State Universities and Colleges', 'name' => 'Bulacan Agricultural State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '53', 'sector' => 'State Universities and Colleges', 'name' => 'Bulacan State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '54', 'sector' => 'State Universities and Colleges', 'name' => 'Central Luzon State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '55', 'sector' => 'State Universities and Colleges', 'name' => 'Don Honorio Ventura Technological State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '56', 'sector' => 'State Universities and Colleges', 'name' => 'Nueva Ecija University of Science and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '57', 'sector' => 'State Universities and Colleges', 'name' => 'Pampanga State Agricultural University', 'created_at' => null, 'updated_at' => null),
            array('id' => '58', 'sector' => 'State Universities and Colleges', 'name' => 'Philippine Merchant Marine Academy', 'created_at' => null, 'updated_at' => null),
            array('id' => '59', 'sector' => 'State Universities and Colleges', 'name' => 'Ramon Magsaysay Technological University', 'created_at' => null, 'updated_at' => null),
            array('id' => '60', 'sector' => 'State Universities and Colleges', 'name' => 'Tarlac College of Agriculture', 'created_at' => null, 'updated_at' => null),
            array('id' => '61', 'sector' => 'State Universities and Colleges', 'name' => 'Tarlac State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '62', 'sector' => 'State Universities and Colleges', 'name' => 'Batangas State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '63', 'sector' => 'State Universities and Colleges', 'name' => 'Cavite State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '64', 'sector' => 'State Universities and Colleges', 'name' => 'Laguna State Polytechnic University', 'created_at' => null, 'updated_at' => null),
            array('id' => '65', 'sector' => 'State Universities and Colleges', 'name' => 'Souther Luzon State University (Southern Luzon Polytechnic College)', 'created_at' => null, 'updated_at' => null),
            array('id' => '66', 'sector' => 'State Universities and Colleges', 'name' => 'University of Rizal System', 'created_at' => null, 'updated_at' => null),
            array('id' => '67', 'sector' => 'State Universities and Colleges', 'name' => 'Marinduque State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '68', 'sector' => 'State Universities and Colleges', 'name' => 'Mindoro State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '69', 'sector' => 'State Universities and Colleges', 'name' => 'Occidental Mindoro State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '70', 'sector' => 'State Universities and Colleges', 'name' => 'Palawan State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '71', 'sector' => 'State Universities and Colleges', 'name' => 'Romblon State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '72', 'sector' => 'State Universities and Colleges', 'name' => 'Western Philippines University', 'created_at' => null, 'updated_at' => null),
            array('id' => '73', 'sector' => 'State Universities and Colleges', 'name' => 'Bicol State College of Applied Sciences and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '74', 'sector' => 'State Universities and Colleges', 'name' => 'Bicol University', 'created_at' => null, 'updated_at' => null),
            array('id' => '75', 'sector' => 'State Universities and Colleges', 'name' => 'Camarines Norte State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '76', 'sector' => 'State Universities and Colleges', 'name' => 'Camarines Sur Polytechnic Colleges', 'created_at' => null, 'updated_at' => null),
            array('id' => '77', 'sector' => 'State Universities and Colleges', 'name' => 'Catanduanes State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '78', 'sector' => 'State Universities and Colleges', 'name' => 'Central Bicol State University of Agriculture (Camarines Sur State Agricultural Colleges)', 'created_at' => null, 'updated_at' => null),
            array('id' => '79', 'sector' => 'State Universities and Colleges', 'name' => 'Dr. Emilio B. Espinosa, Sr. Memorial State College of Agriculture and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '80', 'sector' => 'State Universities and Colleges', 'name' => 'Partido State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '81', 'sector' => 'State Universities and Colleges', 'name' => 'Sorsogon State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '82', 'sector' => 'State Universities and Colleges', 'name' => 'Aklan State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '83', 'sector' => 'State Universities and Colleges', 'name' => 'Capiz State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '84', 'sector' => 'State Universities and Colleges', 'name' => 'Carlos C. Hilado Memorial State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '85', 'sector' => 'State Universities and Colleges', 'name' => 'Central Philippines State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '86', 'sector' => 'State Universities and Colleges', 'name' => 'Guimaras State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '87', 'sector' => 'State Universities and Colleges', 'name' => 'Iloilo Science and Technology University', 'created_at' => null, 'updated_at' => null),
            array('id' => '88', 'sector' => 'State Universities and Colleges', 'name' => 'Northern Negros State College of Science and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '89', 'sector' => 'State Universities and Colleges', 'name' => 'Northern Iloilo State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '90', 'sector' => 'State Universities and Colleges', 'name' => 'Northern Negros State College of Science and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '91', 'sector' => 'State Universities and Colleges', 'name' => 'University of Antique', 'created_at' => null, 'updated_at' => null),
            array('id' => '92', 'sector' => 'State Universities and Colleges', 'name' => 'West Visayas State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '93', 'sector' => 'State Universities and Colleges', 'name' => 'Bohol Island State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '94', 'sector' => 'State Universities and Colleges', 'name' => 'Cebu Normal University', 'created_at' => null, 'updated_at' => null),
            array('id' => '95', 'sector' => 'State Universities and Colleges', 'name' => 'Cebu Technological University', 'created_at' => null, 'updated_at' => null),
            array('id' => '96', 'sector' => 'State Universities and Colleges', 'name' => 'Negros Oriental State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '97', 'sector' => 'State Universities and Colleges', 'name' => 'Siquijor State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '98', 'sector' => 'State Universities and Colleges', 'name' => 'Eastern Samar State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '99', 'sector' => 'State Universities and Colleges', 'name' => 'Eastern Visayas State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '100', 'sector' => 'State Universities and Colleges', 'name' => 'Leyte Normal University', 'created_at' => null, 'updated_at' => null),
            array('id' => '101', 'sector' => 'State Universities and Colleges', 'name' => 'Naval State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '102', 'sector' => 'State Universities and Colleges', 'name' => 'Northwest Samar State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '103', 'sector' => 'State Universities and Colleges', 'name' => 'Palompon Polytechnic State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '104', 'sector' => 'State Universities and Colleges', 'name' => 'Samar State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '105', 'sector' => 'State Universities and Colleges', 'name' => 'Southern Leyte State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '106', 'sector' => 'State Universities and Colleges', 'name' => 'University of Eastern Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '107', 'sector' => 'State Universities and Colleges', 'name' => 'Visayas State University (Leyte State University)', 'created_at' => null, 'updated_at' => null),
            array('id' => '108', 'sector' => 'State Universities and Colleges', 'name' => 'J.H Cerilles State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '109', 'sector' => 'State Universities and Colleges', 'name' => 'Jose Rizal Memorial State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '110', 'sector' => 'State Universities and Colleges', 'name' => 'Western Mindanao State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '111', 'sector' => 'State Universities and Colleges', 'name' => 'Zamboanga City State Polytechnic College', 'created_at' => null, 'updated_at' => null),
            array('id' => '112', 'sector' => 'State Universities and Colleges', 'name' => 'Zamboanga State College of Marine Science and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '113', 'sector' => 'State Universities and Colleges', 'name' => 'Bukidnon State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '114', 'sector' => 'State Universities and Colleges', 'name' => 'Camiguin Polytechnic State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '115', 'sector' => 'State Universities and Colleges', 'name' => 'Central Mindanao University', 'created_at' => null, 'updated_at' => null),
            array('id' => '116', 'sector' => 'State Universities and Colleges', 'name' => 'University of Science and Technology of Southern Philippines-Cagayan de Oro Campus', 'created_at' => null, 'updated_at' => null),
            array('id' => '117', 'sector' => 'State Universities and Colleges', 'name' => 'MSU - Iligan Institute of Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '118', 'sector' => 'State Universities and Colleges', 'name' => 'University of Science and Technology of Southern Philippines-Claveria Campus', 'created_at' => null, 'updated_at' => null),
            array('id' => '119', 'sector' => 'State Universities and Colleges', 'name' => 'Northwestern Mindanao State College of Science and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '120', 'sector' => 'State Universities and Colleges', 'name' => 'Compostela Valley State Colleges', 'created_at' => null, 'updated_at' => null),
            array('id' => '121', 'sector' => 'State Universities and Colleges', 'name' => 'Davao Del Norte State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '122', 'sector' => 'State Universities and Colleges', 'name' => 'Davao Oriental State College of Science and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '123', 'sector' => 'State Universities and Colleges', 'name' => 'Southern Philippines Agri-Business and Marin and Aquatic School of Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '124', 'sector' => 'State Universities and Colleges', 'name' => 'University of Southeastern Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '125', 'sector' => 'State Universities and Colleges', 'name' => 'Cotabato State Univerity (Formerly Cotabato City State Polytechnic College)', 'created_at' => null, 'updated_at' => null),
            array('id' => '126', 'sector' => 'State Universities and Colleges', 'name' => 'Cotabato Foundation College of Science and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '127', 'sector' => 'State Universities and Colleges', 'name' => 'Sultan Kudarat State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '128', 'sector' => 'State Universities and Colleges', 'name' => 'University of Southern Mindanao', 'created_at' => null, 'updated_at' => null),
            array('id' => '129', 'sector' => 'State Universities and Colleges', 'name' => 'Adion Memorial Polytechnic State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '130', 'sector' => 'State Universities and Colleges', 'name' => 'Basilan State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '131', 'sector' => 'State Universities and Colleges', 'name' => 'Mindanao State University', 'created_at' => null, 'updated_at' => null),
            array('id' => '132', 'sector' => 'State Universities and Colleges', 'name' => 'MSU-TAWI-TAWI College of Technology and Oceanography', 'created_at' => null, 'updated_at' => null),
            array('id' => '133', 'sector' => 'State Universities and Colleges', 'name' => 'Sulu State College', 'created_at' => null, 'updated_at' => null),
            array('id' => '134', 'sector' => 'State Universities and Colleges', 'name' => 'TAWI-TAWI Regional Agricultural College', 'created_at' => null, 'updated_at' => null),
            array('id' => '135', 'sector' => 'State Universities and Colleges', 'name' => 'Agusan del Sur State College of Agriculture and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '136', 'sector' => 'State Universities and Colleges', 'name' => 'Caraga State University (Northern Mindanao State Institute of Science and Technology)', 'created_at' => null, 'updated_at' => null),
            array('id' => '137', 'sector' => 'State Universities and Colleges', 'name' => 'Surigao del Sur State University (Surigao del Sur Polytechnic State College)', 'created_at' => null, 'updated_at' => null),
            array('id' => '138', 'sector' => 'State Universities and Colleges', 'name' => 'Surigao State College of Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '139', 'sector' => 'Department of Energy', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '140', 'sector' => 'Department of Environment and Natural Resources', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '141', 'sector' => 'Department of Environment and Natural Resources', 'name' => 'Environmental Management Bureau', 'created_at' => null, 'updated_at' => null),
            array('id' => '142', 'sector' => 'Department of Environment and Natural Resources', 'name' => 'Mines and Geo-Sciences Bureau', 'created_at' => null, 'updated_at' => null),
            array('id' => '143', 'sector' => 'Department of Environment and Natural Resources', 'name' => 'National Mapping and Resource Information Authority', 'created_at' => null, 'updated_at' => null),
            array('id' => '144', 'sector' => 'Department of Environment and Natural Resources', 'name' => 'National Water Resources Board', 'created_at' => null, 'updated_at' => null),
            array('id' => '145', 'sector' => 'Department of Environment and Natural Resources', 'name' => 'Palawan Council for Sustainable Development Staff', 'created_at' => null, 'updated_at' => null),
            array('id' => '146', 'sector' => 'Department of Finance', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '147', 'sector' => 'Department of Finance', 'name' => 'Bureau of Customs', 'created_at' => null, 'updated_at' => null),
            array('id' => '148', 'sector' => 'Department of Finance', 'name' => 'Bureau of Internal Revenue', 'created_at' => null, 'updated_at' => null),
            array('id' => '149', 'sector' => 'Department of Finance', 'name' => 'Bureau of Local Government Finance', 'created_at' => null, 'updated_at' => null),
            array('id' => '150', 'sector' => 'Department of Finance', 'name' => 'Bureau of the Treasury', 'created_at' => null, 'updated_at' => null),
            array('id' => '151', 'sector' => 'Department of Finance', 'name' => 'Central Board of Assessment Appeals', 'created_at' => null, 'updated_at' => null),
            array('id' => '152', 'sector' => 'Department of Finance', 'name' => 'Insurance Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '153', 'sector' => 'Department of Finance', 'name' => 'National Tax Research Center', 'created_at' => null, 'updated_at' => null),
            array('id' => '154', 'sector' => 'Department of Finance', 'name' => 'Privatization and Management Office', 'created_at' => null, 'updated_at' => null),
            array('id' => '155', 'sector' => 'Department of Finance', 'name' => 'Securities and Exchange Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '156', 'sector' => 'Department of Foreign Affairs', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '157', 'sector' => 'Department of Foreign Affairs', 'name' => 'Foreign Service Institute', 'created_at' => null, 'updated_at' => null),
            array('id' => '158', 'sector' => 'Department of Foreign Affairs', 'name' => 'Technical Cooperation Council of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '159', 'sector' => 'Department of Foreign Affairs', 'name' => 'UNESCO National Commission of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '160', 'sector' => 'Department of Health', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '161', 'sector' => 'Department of Health', 'name' => 'Commission on Population', 'created_at' => null, 'updated_at' => null),
            array('id' => '162', 'sector' => 'Department of Health', 'name' => 'National Nutrition Council', 'created_at' => null, 'updated_at' => null),
            array('id' => '163', 'sector' => 'Department of Information and Communications Technology', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '164', 'sector' => 'Department of Information and Communications Technology', 'name' => 'Cybercrime Investigation and Coordination Center', 'created_at' => null, 'updated_at' => null),
            array('id' => '165', 'sector' => 'Department of Information and Communications Technology', 'name' => 'National Privacy Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '166', 'sector' => 'Department of Information and Communications Technology', 'name' => 'National Telecommunications Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '167', 'sector' => 'Department of the Interior and Local Government', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '168', 'sector' => 'Department of the Interior and Local Government', 'name' => 'Bureau of Fire Protection', 'created_at' => null, 'updated_at' => null),
            array('id' => '169', 'sector' => 'Department of the Interior and Local Government', 'name' => 'Bureau of Jail Management and Penology', 'created_at' => null, 'updated_at' => null),
            array('id' => '170', 'sector' => 'Department of the Interior and Local Government', 'name' => 'Local Government Academy', 'created_at' => null, 'updated_at' => null),
            array('id' => '171', 'sector' => 'Department of the Interior and Local Government', 'name' => 'National Police Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '172', 'sector' => 'Department of the Interior and Local Government', 'name' => 'Philippine National Police', 'created_at' => null, 'updated_at' => null),
            array('id' => '173', 'sector' => 'Department of the Interior and Local Government', 'name' => 'Philippine Public Safety College', 'created_at' => null, 'updated_at' => null),
            array('id' => '174', 'sector' => 'Department of Justice', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '175', 'sector' => 'Department of Justice', 'name' => 'Bureau of Corrections', 'created_at' => null, 'updated_at' => null),
            array('id' => '176', 'sector' => 'Department of Justice', 'name' => 'Bureau of Immigration', 'created_at' => null, 'updated_at' => null),
            array('id' => '177', 'sector' => 'Department of Justice', 'name' => 'Land Registration Authority', 'created_at' => null, 'updated_at' => null),
            array('id' => '178', 'sector' => 'Department of Justice', 'name' => 'National Bureau of Investigation', 'created_at' => null, 'updated_at' => null),
            array('id' => '179', 'sector' => 'Department of Justice', 'name' => 'Office of the Government Corporate Counsel', 'created_at' => null, 'updated_at' => null),
            array('id' => '180', 'sector' => 'Department of Justice', 'name' => 'Office of the Solicitor General', 'created_at' => null, 'updated_at' => null),
            array('id' => '181', 'sector' => 'Department of Justice', 'name' => 'Parole and Probation Administration', 'created_at' => null, 'updated_at' => null),
            array('id' => '182', 'sector' => 'Department of Justice', 'name' => 'Presidential Commission on Good Government', 'created_at' => null, 'updated_at' => null),
            array('id' => '183', 'sector' => 'Department of Justice', 'name' => 'Public Attorney\'s Office', 'created_at' => null, 'updated_at' => null),
            array('id' => '184', 'sector' => 'Department of Labor and Employment', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '185', 'sector' => 'Department of Labor and Employment', 'name' => 'Institute of Labor Studies', 'created_at' => null, 'updated_at' => null),
            array('id' => '186', 'sector' => 'Department of Labor and Employment', 'name' => 'National Counciliation and Mediation Board', 'created_at' => null, 'updated_at' => null),
            array('id' => '187', 'sector' => 'Department of Labor and Employment', 'name' => 'National Labor Relations Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '188', 'sector' => 'Department of Labor and Employment', 'name' => 'National Maritime Polytechnic', 'created_at' => null, 'updated_at' => null),
            array('id' => '189', 'sector' => 'Department of Labor and Employment', 'name' => 'National Wages and Productivity Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '190', 'sector' => 'Department of Labor and Employment', 'name' => 'Philippine Overseas Employment Administration', 'created_at' => null, 'updated_at' => null),
            array('id' => '191', 'sector' => 'Department of Labor and Employment', 'name' => 'Professional Regulation Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '192', 'sector' => 'Department of Labor and Employment', 'name' => 'Overseas Workers Welfare Administration', 'created_at' => null, 'updated_at' => null),
            array('id' => '193', 'sector' => 'Department of National Defense', 'name' => 'Office of the Secretary - Proper', 'created_at' => null, 'updated_at' => null),
            array('id' => '194', 'sector' => 'Department of National Defense', 'name' => 'Government Arsenal', 'created_at' => null, 'updated_at' => null),
            array('id' => '195', 'sector' => 'Department of National Defense', 'name' => 'National Defense College of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '196', 'sector' => 'Department of National Defense', 'name' => 'Office of the Civil Defense', 'created_at' => null, 'updated_at' => null),
            array('id' => '197', 'sector' => 'Department of National Defense', 'name' => 'Philippine Veterans Affairs Office (PVAO) - Proper', 'created_at' => null, 'updated_at' => null),
            array('id' => '198', 'sector' => 'Department of National Defense', 'name' => 'Veterans Memorial Medical center', 'created_at' => null, 'updated_at' => null),
            array('id' => '199', 'sector' => 'Department of National Defense', 'name' => 'Armed Forces of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '200', 'sector' => 'Department of National Defense', 'name' => 'Philippine Army (Land Forces)', 'created_at' => null, 'updated_at' => null),
            array('id' => '201', 'sector' => 'Department of National Defense', 'name' => 'Philippines Air Force (Air Forces)', 'created_at' => null, 'updated_at' => null),
            array('id' => '202', 'sector' => 'Department of National Defense', 'name' => 'Philippines Navy (Naval Forces)', 'created_at' => null, 'updated_at' => null),
            array('id' => '203', 'sector' => 'Department of National Defense', 'name' => 'General Headquarters. AFP and AFP Wide Support and Separate Units(AFPWSSUS)', 'created_at' => null, 'updated_at' => null),
            array('id' => '204', 'sector' => 'Department of Science and Technology', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '205', 'sector' => 'Department of Science and Technology', 'name' => 'Advance Science and Technology Institute', 'created_at' => null, 'updated_at' => null),
            array('id' => '206', 'sector' => 'Department of Science and Technology', 'name' => 'Food and Nutrition Research Institute', 'created_at' => null, 'updated_at' => null),
            array('id' => '207', 'sector' => 'Department of Science and Technology', 'name' => 'Forest Products Research and Development Institute', 'created_at' => null, 'updated_at' => null),
            array('id' => '208', 'sector' => 'Department of Science and Technology', 'name' => 'Industrial Technology Development Institute', 'created_at' => null, 'updated_at' => null),
            array('id' => '209', 'sector' => 'Department of Science and Technology', 'name' => 'Metals Industry Research and Development Center', 'created_at' => null, 'updated_at' => null),
            array('id' => '210', 'sector' => 'Department of Science and Technology', 'name' => 'National Academy of Science and Technology', 'created_at' => null, 'updated_at' => null),
            array('id' => '211', 'sector' => 'Department of Science and Technology', 'name' => 'National Research Council of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '212', 'sector' => 'Department of Science and Technology', 'name' => 'Philippine Atmospheric, Geophysical and Astronomical Sevices Administration', 'created_at' => null, 'updated_at' => null),
            array('id' => '213', 'sector' => 'Department of Science and Technology', 'name' => 'Philippine Council for Agriculture, Aquatic and Natural Resources Research and Development', 'created_at' => null, 'updated_at' => null),
            array('id' => '214', 'sector' => 'Department of Science and Technology', 'name' => 'Philippine Council for Health Research and Development', 'created_at' => null, 'updated_at' => null),
            array('id' => '215', 'sector' => 'Department of Science and Technology', 'name' => 'Philippine Council for Industry and Energy and Emerging Technology Research and Development', 'created_at' => null, 'updated_at' => null),
            array('id' => '216', 'sector' => 'Department of Science and Technology', 'name' => 'Philippine Institute of Volcanology and Seismology', 'created_at' => null, 'updated_at' => null),
            array('id' => '217', 'sector' => 'Department of Science and Technology', 'name' => 'Philippine Nuclear Research Institute', 'created_at' => null, 'updated_at' => null),
            array('id' => '218', 'sector' => 'Department of Science and Technology', 'name' => 'Philippine Science High School', 'created_at' => null, 'updated_at' => null),
            array('id' => '219', 'sector' => 'Department of Science and Technology', 'name' => 'Philippine Textile Research Institute', 'created_at' => null, 'updated_at' => null),
            array('id' => '220', 'sector' => 'Department of Science and Technology', 'name' => 'Science Education Institute', 'created_at' => null, 'updated_at' => null),
            array('id' => '221', 'sector' => 'Department of Science and Technology', 'name' => 'Science and Technology Information Institute', 'created_at' => null, 'updated_at' => null),
            array('id' => '222', 'sector' => 'Department of Science and Technology', 'name' => 'Technology Application and Promotion Institute', 'created_at' => null, 'updated_at' => null),
            array('id' => '223', 'sector' => 'Department of Social Welfare and Development', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '224', 'sector' => 'Department of Social Welfare and Development', 'name' => 'Council for the Welfare of Children', 'created_at' => null, 'updated_at' => null),
            array('id' => '225', 'sector' => 'Department of Social Welfare and Development', 'name' => 'Inter-Country Adoption Board', 'created_at' => null, 'updated_at' => null),
            array('id' => '226', 'sector' => 'Department of Social Welfare and Development', 'name' => 'National Council on Disability Affairs', 'created_at' => null, 'updated_at' => null),
            array('id' => '227', 'sector' => 'Department of Social Welfare and Development', 'name' => 'Juvenile Justice and Welfare Council', 'created_at' => null, 'updated_at' => null),
            array('id' => '228', 'sector' => 'Department of Tourism', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '229', 'sector' => 'Department of Tourism', 'name' => 'Intramuros Administration', 'created_at' => null, 'updated_at' => null),
            array('id' => '230', 'sector' => 'Department of Tourism', 'name' => 'National Parks Development Committee', 'created_at' => null, 'updated_at' => null),
            array('id' => '231', 'sector' => 'Department of Trade and Industry', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '232', 'sector' => 'Department of Trade and Industry', 'name' => 'Board of Investments', 'created_at' => null, 'updated_at' => null),
            array('id' => '233', 'sector' => 'Department of Trade and Industry', 'name' => 'Construction Industry Authority of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '234', 'sector' => 'Department of Trade and Industry', 'name' => 'Design Center of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '235', 'sector' => 'Department of Trade and Industry', 'name' => 'Philippine Trade Training Center', 'created_at' => null, 'updated_at' => null),
            array('id' => '236', 'sector' => 'Department of Transportation', 'name' => 'Office of the Secretary', 'created_at' => null, 'updated_at' => null),
            array('id' => '237', 'sector' => 'Department of Transportation', 'name' => 'Civil Aeronautics Board', 'created_at' => null, 'updated_at' => null),
            array('id' => '238', 'sector' => 'Department of Transportation', 'name' => 'Maritime Industry Authority', 'created_at' => null, 'updated_at' => null),
            array('id' => '239', 'sector' => 'Department of Transportation', 'name' => 'Office of Transportation Cooperatives', 'created_at' => null, 'updated_at' => null),
            array('id' => '240', 'sector' => 'Department of Transportation', 'name' => 'Office for Transportation Security', 'created_at' => null, 'updated_at' => null),
            array('id' => '241', 'sector' => 'Department of Transportation', 'name' => 'Philippine Coast Guard', 'created_at' => null, 'updated_at' => null),
            array('id' => '242', 'sector' => 'Department of Transportation', 'name' => 'Toll Regulatory Board', 'created_at' => null, 'updated_at' => null),
            array('id' => '243', 'sector' => 'National Economic and Development Authority', 'name' => 'Office of Director-General', 'created_at' => null, 'updated_at' => null),
            array('id' => '244', 'sector' => 'National Economic and Development Authority', 'name' => 'Philippine National Volunteer Service Coordinating Agency', 'created_at' => null, 'updated_at' => null),
            array('id' => '245', 'sector' => 'National Economic and Development Authority', 'name' => 'Public-Private Partnership Center of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '246', 'sector' => 'National Economic and Development Authority', 'name' => 'Philippine Statistical Research and Training  Institute', 'created_at' => null, 'updated_at' => null),
            array('id' => '247', 'sector' => 'National Economic and Development Authority', 'name' => 'Tariff Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '248', 'sector' => 'National Economic and Development Authority', 'name' => 'Philippines Statistic Authority', 'created_at' => null, 'updated_at' => null),
            array('id' => '249', 'sector' => 'Presidential Communication Operations Office', 'name' => 'Presidential Communication Operations Office (Proper)', 'created_at' => null, 'updated_at' => null),
            array('id' => '250', 'sector' => 'Presidential Communication Operations Office', 'name' => 'Bureau of Broadcast Services', 'created_at' => null, 'updated_at' => null),
            array('id' => '251', 'sector' => 'Presidential Communication Operations Office', 'name' => 'Bureau of Communication Services', 'created_at' => null, 'updated_at' => null),
            array('id' => '252', 'sector' => 'Presidential Communication Operations Office', 'name' => 'National Printing Office', 'created_at' => null, 'updated_at' => null),
            array('id' => '253', 'sector' => 'Presidential Communication Operations Office', 'name' => 'News and Information Bureau', 'created_at' => null, 'updated_at' => null),
            array('id' => '254', 'sector' => 'Presidential Communication Operations Office', 'name' => 'Philippine Information Agency', 'created_at' => null, 'updated_at' => null),
            array('id' => '255', 'sector' => 'Presidential Communication Operations Office', 'name' => 'Presidential Broadcast Staff (RTVM)', 'created_at' => null, 'updated_at' => null),
            array('id' => '256', 'sector' => 'Other Executive Office', 'name' => 'Anti-Money Laudering Council', 'created_at' => null, 'updated_at' => null),
            array('id' => '257', 'sector' => 'Other Executive Office', 'name' => 'Climate Change Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '258', 'sector' => 'Other Executive Office', 'name' => 'Commission on Filipinos Overseas', 'created_at' => null, 'updated_at' => null),
            array('id' => '259', 'sector' => 'Other Executive Office', 'name' => 'Commission on Higher Edducation', 'created_at' => null, 'updated_at' => null),
            array('id' => '260', 'sector' => 'Other Executive Office', 'name' => 'Commission on the Filipino Language', 'created_at' => null, 'updated_at' => null),
            array('id' => '261', 'sector' => 'Other Executive Office', 'name' => 'Cooperative Development Authority', 'created_at' => null, 'updated_at' => null),
            array('id' => '262', 'sector' => 'Other Executive Office', 'name' => 'Dangerous Drugs Board', 'created_at' => null, 'updated_at' => null),
            array('id' => '263', 'sector' => 'Other Executive Office', 'name' => 'Energy Regulatory Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '264', 'sector' => 'Other Executive Office', 'name' => 'Fertilizer and Pesticide Authority', 'created_at' => null, 'updated_at' => null),
            array('id' => '265', 'sector' => 'Other Executive Office', 'name' => 'Film Development Council of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '266', 'sector' => 'Other Executive Office', 'name' => 'Games and Amusements Board', 'created_at' => null, 'updated_at' => null),
            array('id' => '267', 'sector' => 'Other Executive Office', 'name' => 'Governance Commission for Government-Owned and Controlled Operations', 'created_at' => null, 'updated_at' => null),
            array('id' => '268', 'sector' => 'Other Executive Office', 'name' => 'Housing and Land Use Regulatory Board', 'created_at' => null, 'updated_at' => null),
            array('id' => '269', 'sector' => 'Other Executive Office', 'name' => 'Housing and Urban Development Coordinating Council', 'created_at' => null, 'updated_at' => null),
            array('id' => '270', 'sector' => 'Other Executive Office', 'name' => 'Mindanao Development Authority', 'created_at' => null, 'updated_at' => null),
            array('id' => '271', 'sector' => 'Other Executive Office', 'name' => 'Movie and Television Review and Classification Board', 'created_at' => null, 'updated_at' => null),
            array('id' => '272', 'sector' => 'Other Executive Office', 'name' => 'National Anti-Poverty Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '273', 'sector' => 'Other Executive Office', 'name' => 'National Commission for Culture and the Arts (Proper)', 'created_at' => null, 'updated_at' => null),
            array('id' => '274', 'sector' => 'Other Executive Office', 'name' => 'National Historical Commission of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '275', 'sector' => 'Other Executive Office', 'name' => 'National Library of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '276', 'sector' => 'Other Executive Office', 'name' => 'National Archives of the Philippines', 'created_at' => null, 'updated_at' => null),
            array('id' => '277', 'sector' => 'Other Executive Office', 'name' => 'National Commission on Indigenous Peoples', 'created_at' => null, 'updated_at' => null),
            array('id' => '278', 'sector' => 'Other Executive Office', 'name' => 'National Commission on Muslim Filipinos (Office on Muslim Affairs)', 'created_at' => null, 'updated_at' => null),
            array('id' => '279', 'sector' => 'Other Executive Office', 'name' => 'National Intelligence Coordinating Agency', 'created_at' => null, 'updated_at' => null),
            array('id' => '280', 'sector' => 'Other Executive Office', 'name' => 'National Security Council', 'created_at' => null, 'updated_at' => null),
            array('id' => '281', 'sector' => 'Other Executive Office', 'name' => 'National Youth Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '282', 'sector' => 'Other Executive Office', 'name' => 'Office of the Presidential Adviser on the Peace Process', 'created_at' => null, 'updated_at' => null),
            array('id' => '283', 'sector' => 'Other Executive Office', 'name' => 'Optical Media Board', 'created_at' => null, 'updated_at' => null),
            array('id' => '284', 'sector' => 'Other Executive Office', 'name' => 'Pasig River Rehabilitation Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '285', 'sector' => 'Other Executive Office', 'name' => 'Philippines Commission on Women (National Commission on the Role of Filipino Women)', 'created_at' => null, 'updated_at' => null),
            array('id' => '286', 'sector' => 'Other Executive Office', 'name' => 'Philippine Competition Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '287', 'sector' => 'Other Executive Office', 'name' => 'Philippine Drug Enforcement Agency', 'created_at' => null, 'updated_at' => null),
            array('id' => '288', 'sector' => 'Other Executive Office', 'name' => 'Philippine Racing Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '289', 'sector' => 'Other Executive Office', 'name' => 'Philippine Sports Commission', 'created_at' => null, 'updated_at' => null),
            array('id' => '290', 'sector' => 'Other Executive Office', 'name' => 'Philippine Commission for the Urban Poor', 'created_at' => null, 'updated_at' => null),
            array('id' => '291', 'sector' => 'Other Executive Office', 'name' => 'Presidential Legislative Liaison Office', 'created_at' => null, 'updated_at' => null),
            array('id' => '292', 'sector' => 'Other Executive Office', 'name' => 'Presidential Management Staff', 'created_at' => null, 'updated_at' => null),
            array('id' => '293', 'sector' => 'Other Executive Office', 'name' => 'Technical Education and Skills Development Authority', 'created_at' => null, 'updated_at' => null)
        ]);
    }
}
